fixing docker compose

diff --git a/.github/workflows/docker-publish.yaml b/.github/workflows/docker-publish.yaml
--- a/.github/workflows/docker-publish.yaml
+++ b/.github/workflows/docker-publish.yaml
@@ -45,7 +45,12 @@ jobs:
       - name: Check Docker and Docker Compose
         run: |
           docker --version
-          docker-compose --version
+          docker-compose --version || echo "docker-compose not found"
+
+      - name: Install Docker Compose
+        run: |
+          sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+          sudo chmod +x /usr/local/bin/docker-compose
 
       - name: Docker Compose Build
         working-directory: .
@@ -60,7 +65,4 @@ jobs:
           docker tag ${{ secrets.DOCKER_USERNAME }}/user-system-api:latest ${{ secrets.DOCKER_USERNAME }}/user-system-api:${{github.run_id}}
           docker push ${{ secrets.DOCKER_USERNAME }}/naming-server:${{github.run_id}}
           docker push ${{ secrets.DOCKER_USERNAME }}/naming-server:latest
-          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{github.run_id}}
-          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
-          docker push ${{ secrets.DOCKER_USERNAME }}/user-system-api:${{github.run_id}}
-          docker push ${{ secrets.DOCKER_USERNAME }}/user-system-api:latest
+          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{
